core/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('my_learning', views.learning, name='my_learning')
    # path('face_authentication/', views.face_authentication, name='face_authentication'),
]

course_recommendation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import index, contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('', include('core.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

item/urls.py
from django.urls import path, include
from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
]

core/models.py
from django.db import models
# from django.contrib.auth.models import User
from item.models import Item, Category
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self, username, email, password, **extra_fields):

        if not username:
            raise ValueError('User must have a valid username')
        if not email:
            raise ValueError('User must have a email')
        if not password:
            raise ValueError('User must have a password')
        # if not image:
        #     raise ValueError('User must have a image')
        
        user = self.model(username=username, email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        # user.is_active = True
        # user.is_staff = True
        user.save(using=self._db)
        return user
    
    def create_superuser(self, username,email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        return self.create_user(username, email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    # image = models.ImageField(upload_to='users', null=True, blank=True)

    # Add additional fields to the user model
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email", "password"]#, "image"]
    objects = UserManager()

    def __str__(self):
        return "@{}".format(self.username)
    
class Order(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.id)
    
class Userimage(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='users', blank=False, null=False)
    
class Order_Item(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, blank=True)
    buy_date = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=100, null=True)

class Camera_image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='login_folder', blank=True, null=True)

# class Profile(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     preferred_category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

core/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
# from django.contrib.auth.models import User
# from django.contrib.auth import get_user_model

# class LoginForm(AuthenticationForm):

#     username = forms.CharField(widget=forms.TextInput(attrs={
#         'placeholder': 'Your Username',
#         'name': 'username',
#         'class': 'w-full py-4 px-6 rounded-xl'}))

#     password = forms.CharField(widget=forms.PasswordInput(attrs={
#         'placeholder': 'Your Password',
#         'name': 'password',
#         'class': 'w-full py-4 px-6 rounded-xl'}))
    
#     img = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'id': 'img'}))

#     def clean_img(self):
#         img_data = self.cleaned_data['img']
#         if not img_data:
#             raise forms.ValidationError("Image data is required.")
#         # Additional validation logic for the image data if needed
#         return img_data

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'}), label='Username')

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl'}), label='Password')
    
    img = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'img'}))

    # def clean_img(self):
    #     img_data = self.cleaned_data['img']
    #     if not img_data:
    #         raise forms.ValidationError("Image data is required.")
    #     # Additional validation logic for the image data if needed
    #     return img_data


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2','image')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'}))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your Email',
        'class': 'w-full py-4 px-6 rounded-xl'}))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl'}))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
        'class': 'w-full py-4 px-6 rounded-xl'}))

    image = forms.ImageField()

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from item.models import Category, Item
from .forms import SignupForm, LoginForm
from .models import Order, Order_Item, User, Userimage, Camera_image
# from django.contrib.User import User
import io
from django.conf import settings
import numpy as np
import face_recognition
from PIL import Image
import urllib.request as ur

import base64
from base64 import decodestring, b64decode

# Create your views here.
def index(request):
    recommended = []
    if request.user.is_authenticated:
        customer = User.objects.get(username=request.user.username)
        recommended_category = get_user_preferred_category(customer)
        if recommended_category:
        # profile = Profile.objects.get(user=customer)
        # recommended_category = profile.preferred_category
            recommended_all = Item.objects.filter(category=recommended_category)

            order = Order.objects.get(user=customer)
            items = Order_Item.objects.filter(order=order)

            for item in recommended_all:
                if item not in items:
                    recommended.append(item)
                if len(recommended)==3:
                    break

    items = Item.objects.all().order_by('price')#.values()
    categories = Category.objects.all()

    a = dict()
    a['items'] = items
    a['categories'] = categories
    a['count'] = int(len(recommended))
    a['recommended'] = recommended

    return render(request, 'core/index.html', context=a)

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            password1 = form.cleaned_data.get("password1")
            password2 = form.cleaned_data.get("password2")
            image = form.cleaned_data.get("image")
            user = User.objects.get(username=username)
            order = Order(user=user)
            order.save()
            user_img = Userimage(user=user, img=image)
            user_img.save()
            # profile = Profile(user=user)
            # profile.save()
            user = authenticate(username=username,password=password1)
            login(request,user)        
            return redirect('/')
        else:
            a=dict()
            a['form'] = form
            return render(request, 'core/signup.html', context=a)
        
    else:
        form = SignupForm()
        
    a=dict()
    a['form'] = form
    return render(request, 'core/signup.html', context=a)


# def login_view(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST, request.FILES)
#         # print(form)
#         print('ishan  ',request.POST.get("img"))
#         if form.is_valid():
#             # form.save()
#             print(123)
#             username = form.cleaned_data["username"]
#             password = form.cleaned_data["password"]
#             img = form.cleaned_data["img"]
#             user = authenticate(request, username=username, password=password)
#             if user is not None:
#                 # customer = User.objects.get(username=username)
#                 customer=user
#                 img = img.replace('data:image/png;base64,', '') 
#                 # if face_detect(img, customer):
#                 if test_compare_images(user, Userimage.objects.get(user=customer).img.path,img,0.8):
#                     login(request, user)
#                     # get_user_preferred_category(customer)
#                     return redirect('/')
#                 else:
#                     form = LoginForm()
#                     return render(request, "core/login.html", {'message': 'Face does not match with your credentials.', 'form': form})
#             else:
#                 form = LoginForm()
#                 return render(request, "core/login.html", {'message': 'Username and Password does not match.', 'form': form})

#     else:
#         form = LoginForm()
#         return render(request, "core/login.html", {'form': form})
def login_view(request):
    if request.method == 'POST':
        # if form.is_valid():
        # print(123)
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            img = request.POST.get("img")
            img = img.replace('data:image/png;base64,', '')
            customer = user
            if test_compare_faces(Userimage.objects.get(user=customer).img.path, img):
                login(request, user)
                return redirect('/')
            else:
                form = LoginForm()
                # form.add_error(None, 'Face does not match with your credentials.')
        else:
            form = LoginForm()
            # form.add_error(None, 'Username and Password do not match.')
    else:
        form = LoginForm()

    return render(request, "core/login.html", {'form': form})

def login_view2(request):
    if request.method == 'POST':
        # print(request.POST.dict())
        form = LoginForm(request.POST)
        print(form)
        if form.is_valid():
            print(123)
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                img = form.cleaned_data.get("img")
                img = img.replace('data:image/png;base64,', '')
                customer = user
                if test_compare_images(user, Userimage.objects.get(user=customer).img.path, img, 0.8):
                    login(request, user)
                    return redirect('/')
                else:
                    form = LoginForm()
                    form.add_error('img', 'Face does not match with your credentials.')
            else:
                form = LoginForm()
                form.add_error(None, 'Username and Password do not match.')
        else:
            # Handle the case when the form is not valid
            # print("invalid form")
            # print(form.errors) 
            form = LoginForm()
            # return render(request, "core/login.html", {'form': form})
    else:
        form = LoginForm()

    return render(request, "core/login.html", {'form': form})
    
# import face_recognition
# from PIL import Image
import io
from urllib.request import urlopen
import tempfile
from base64 import decodestring


import base64
import io
from PIL import Image

def convert_base64_to_image(base64_string):
    # Decode the base64 string into binary data
    image_data = base64.b64decode(base64_string)

    # Create a BytesIO stream to work with the binary data
    stream = io.BytesIO(image_data)

    # Open the image using PIL (Python Imaging Library)
    image = Image.open(stream)

    return image

# Example usage
# base64_string = "your_base64_encoded_image_string"

# Convert base64 to image
# image = convert_base64_to_image(base64_string)

# image_path = "path_to_save_image.jpg"  # Provide the desired file path
# image.save(image_path, "JPEG")


# def test_face_detect(url_image, png_image_path):
#     import face_recognition

import uuid
from django.core.files.base import ContentFile

def convert_base64_to_image(base64_string):
    # Decode the base64 string into binary data
    image_data = base64.b64decode(base64_string)

    # Create a BytesIO stream to work with the binary data
    stream = io.BytesIO(image_data)

    # Open the image using PIL (Python Imaging Library)
    image = Image.open(stream)

    return image

# def base64_file(data, name=None):
#     _format, _img_str = data.split(';base64,')
#     _name, ext = _format.split('/')
#     # if not name:
#     #     name = _name.split(":")[-1]
#     filename = str(uuid.uuid4())
#     return ContentFile(base64.b64decode(_img_str), name='{}.{}'.format(filename, 'jpeg')), filename
import cv2
def test_compare_faces(jpeg_image_path, base64_image):
    # Load the JPEG image
    jpeg_image = cv2.imread(jpeg_image_path)

    # Convert the base64 image to numpy array
    base64_image = base64_image.split(';base64,')[1]
    # print(base64_image)
    base64_data = base64.b64decode(base64_image)
    nparr = np.frombuffer(base64_data, np.uint8)
    base64_image = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

    # Convert the images to RGB format
    jpeg_image_rgb = cv2.cvtColor(jpeg_image, cv2.COLOR_BGR2RGB)
    base64_image_rgb = cv2.cvtColor(base64_image, cv2.COLOR_BGR2RGB)

    # Detect faces in the images
    jpeg_face_locations = face_recognition.face_locations(jpeg_image_rgb)
    base64_face_locations = face_recognition.face_locations(base64_image_rgb)

    # Encode the face landmarks
    jpeg_face_encodings = face_recognition.face_encodings(jpeg_image_rgb, jpeg_face_locations)
    base64_face_encodings = face_recognition.face_encodings(base64_image_rgb, base64_face_locations)

    if len(base64_face_encodings)==0:
        return False

    # Compare the face encodings
    results = face_recognition.compare_faces(jpeg_face_encodings, base64_face_encodings[0])

    return results


def test_compare_images(user, registered_image, login_image, threshold):
    # return True
    # Load the images
    # print(login_image)
    login_image = login_image[login_image.find(",")+1:]
    # login_image = convert_base64_to_image(login_image)
    # login_image = ContentFile(base64.b64decode(login_image))
    filename = str(uuid.uuid4())

    image = convert_base64_to_image(login_image)

    cam_img =Camera_image(user=user, img=image)
    cam_img.save()
    # cam_img.img.save('{}.png'.format(filename), login_image)

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss-carousel@0.2.0/dist/carousel.min.css" rel="stylesheet"> -->
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" /> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/tailwindcss-carousel@0.2.0/dist/carousel.min.js"></script> -->
    <title>{%block title%} {%endblock%} | My Course</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">My Course</a>
        <div class="space-x-6">
            {%if request.user.is_authenticated%}
            <a href="{%url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Log Out</a>
            <a href="{%url 'core:my_learning' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">My Learnings</a>
            {%else%}
            <a href="{%url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
            <a href="{%url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">LogIn</a>
            {%endif%}
        </div>
    </nav>
    <div class="px-6 py-6">
        {%block content%}
        {%endblock%}
    </div>
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">snlkckl snlkckl snlkckl snlkckl snlkckl snlkckl snlkckl snlkckl snlkckl snlkckl</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{%url 'core:contact'%}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

core/templates/core/cart.html
{% extends 'core/base.html'%}

{%block title%}
My Learnings
{%endblock%}

{%block content%}
<section class="h-100" style="background-color: #eee;">
    <div class="container h-100 py-5">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-10">
  
          <div class="d-flex justify-content-between align-items-center mb-4">
            <h1 class="fw-normal mb-0 text-black">My Learning</h1>
          </div>
  
          {%for it in items%}
          <div class="card rounded-3 mb-4">
            <div class="card-body p-4">
              <div class="row d-flex justify-content-between align-items-center">
                <div class="col-md-2 col-lg-2 col-xl-2">
                  <img
                    src="{{it.item.img.url}}"
                    class="img-fluid rounded-3" alt="item"
                    style="width: 100px; height: 100px;">
                </div>
                <div class="col-md-3 col-lg-3 col-xl-3">
                  <p class="lead fw-normal mb-2">{{it.item.name}}</p>
                </div>
                
                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Continue</a>
                </div>
              </div>
            </div>
          </div>
  
          {%endfor%}

  
        </div>
      </div>
    </div>
  </section>

{%endblock%}

core/templates/core/contact.html
{% extends 'core/base.html'%}

{%block content%}
    <h3>The contact page</h3>
{%endblock%}

core/templates/core/face_authentication.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>Face Authentication</title>
    </head>

    <body>
        <center>
            <h1>Please match your face to login</h1>
            <button id="start-camera">Start Camera</button>
            <video id="video" width="320" height="240" autoplay></video>
            <button id="click-photo">Click Photo</button>
            <canvas id="canvas" width="320" height="240" name="canvas"></canvas>
            {%if message%}
                <p>{{message}}</p>
            {%endif%}
            <form action="." method="post" enctype="multipart/form-data">
                {%csrf_token%}
                <input type="hidden" name="img" id="img" value="">
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">LogIn</button>
            </form>
        </center>

        <script>
            let camera_button = document.querySelector("#start-camera");
            let video = document.querySelector("#video");
            let click_button = document.querySelector("#click-photo");
            let canvas = document.querySelector("#canvas");

            camera_button.addEventListener('click', async function () {
                let stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: false });
                video.srcObject = stream;
            });

            click_button.addEventListener('click', function () {
                canvas.getContext('2d').drawImage(video, 0, 0, canvas.width, canvas.height);
                let image_data_url = canvas.toDataURL('image/jpeg');
                let ele = document.getElementById('img');
                ele.setAttribute('value', image_data_url)
                // data url of the image
                console.log(image_data_url);
            });
        </script>
    </body>

</html>

core/templates/core/index.html
{% extends 'core/base.html'%}

{%block title%}
    Welcome
{% endblock %}

{%block content%}
    {% if count > 0 %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Recommended for You</h2>
        <div class="grid grid-cols-3 gap-3">
            {%for item in recommended%}
            <div class="border-2">
                <a href="{%url 'item:detail' item.id%}">
                    <div class="flex justify-center">
                        <img src="{{item.img.url}}" alt="img1" class="rounded-t-xl" style="height: 250px; width: 70%;">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2>
                        <p class="text-gray-500">Price: ₹{{item.price}}</p>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>
    </div>
    {%endif%}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">All Courses</h2>
        <div class="grid grid-cols-3 gap-3">
            {%for item in items%}
            <div class="border-2">
                <a href="{%url 'item:detail' item.id%}">
                    <div class="flex justify-center">
                        <img src="{{item.img.url}}" alt="img1" class="rounded-t-xl" style="height: 250px; width: 70%;">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2>
                        <p class="text-gray-500">Price: ₹{{item.price}}</p>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {%for category in categories%}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{category.name}}</h2>
                        <p class="text-gray-500">{{category.items.count}} items</p>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>
    </div>

{%endblock%}

core/templates/core/login.html
{%extends 'core/base.html'%}

{%block title%}
LogIn
{%endblock%}

{%block content%}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
  <h1 class="mb-6 text-3xl">
    <center>LogIn</center>
  </h1>
  <!-- {%if message%}
    <center>
        <div class="flex items-center justify-between max-w-xs p-4 bg-white border rounded-md shadow-sm shadow-yellow-600">
            <div class="flex items-center">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 text-yellow-600" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd"
                  d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z"
                  clip-rule="evenodd" />
              </svg>
              <p class="ml-3 text-sm font-bold text-yellow-600">{{message}}</p>
            </div>
            <span class="inline-flex items-center cursor-pointer">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-gray-600" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </span>
          </div>
          </center> 
    {%endif%}-->


  <form action="." method="post" enctype="multipart/form-data">

    {%csrf_token%}

    {%if form.errors or form.non_feild_errors%}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
      {%for feild in form%}
      {{feild.errors}}
      {%endfor%}
      {{form.non_field_errors}}
    </div>
    {%endif%}

    <div class="mb-3">
      <label for="" class="inline-block mb-2">Username</label><br>
      {{form.username}}
      {% if form.username.errors %}
      <ul class="errorlist">
        {% for error in form.username.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="" class="inline-block mb-2">Password</label><br>
      {{form.password}}
      {% if form.password.errors %}
      <ul class="errorlist">
        {% for error in form.password.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>

    {{form.img.as_hidden}}

    <br>

    <!--  -->
    <center>

      <button type="button" id="start-camera"
        class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Start Camera</button>
      <br><br>
      <video id="video" width="320" height="240" autoplay></video>
      <br>
      <button type="button" id="click-photo"
        class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Click Photo</button>
      <br><br>
      <canvas id="canvas" width="320" height="240" name="canvas"></canvas>
      <br>

    </center>
    <!--  -->
    <center>
      <button type="submit" id='submit-button'
        class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </center>
  </form>
</div>


<script>
  let camera_button = document.querySelector("#start-camera");
  let video = document.querySelector("#video");
  let click_button = document.querySelector("#click-photo");
  let canvas = document.querySelector("#canvas");

  camera_button.addEventListener('click', async function () {
    let stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: false });
    video.srcObject = stream;
  });

  click_button.addEventListener('click', function () {
    canvas.getContext('2d').drawImage(video, 0, 0, canvas.width, canvas.height);
    let image_data_url = canvas.toDataURL('image/jpeg');
    let ele = document.querySelector('#id_img');
    ele.value = image_data_url.toString();

    let username = document.querySelector("#id_username").value;
    let password = document.querySelector("#id_password").value;

    console.log("Username:", username);
    console.log("Password:", password);
    console.log(ele.value);
  });

  // });
</script>




{%endblock%}